---
name: test dependent modules

on:
  workflow_dispatch:

jobs:
  build-and-test-job:
    name: Build distribution
    runs-on: ubuntu-20.04
    container:
      image: perldocker/perl-tester:5.36
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        env:
          AUTHOR_TESTING: 0
          AUTOMATED_TESTING: 1
          EXTENDED_TESTING: 1
          RELEASE_TESTING: 1
        run: auto-build-and-test-dist
      - name: install action prereqs
        run: cpm install -g Test::DependentModules IO::All
      - name: generate dep prereqs
        run: perl -Ixt -MDepReqs -e 'DepReqs->run'
      - name: install dep prereqs
        run: cpm install -g --cpanfile xt/cpanfile --show-build-log-on-failure
      - name: Test Dependents
        env:
          TEST_DEPENDENTS: 1
          PERL_TEST_DM_CPAN_VERBOSE: 1
        run: prove -l xt/dependent-modules.t
